### ISSUE TITLE
Some questions about reproducing your code

### ISSUE THREAD

**Issue by lemOnpkp** [aravind2060/HadoopAndHiveforLargeScaleDataAnalysis#1]
sorry to bother you. I think you have done a really good job! I want to reproduce your code to make a reaserch about the weather. Can you upload again your ReadMe.md? Or can you give me your email so that I can ask you some questions if I have trouble reproducing your code? I would appreciate it if you could give me your email. Thank you sooooo much!

**Comment by aravind2060** [comment]
Hey! I'd be happy to help you. My email is aravind4532@gmail.com. I need to create a fresh readme.md, but the old readme.md will be accessible in history. Keep in mind that it's experimental. I have written the old readme keeping in mind that each step can be executed with either mapreduce or hive.    The steps for execution are in /docs.

**Comment by lemOnpkp** [comment]
> Hey! I'd be happy to help you. My email is [aravind4532@gmail.com](mailto:aravind4532@gmail.com). I need to create a fresh readme.md, but the old readme.md will be accessible in history. Keep in mind that it's experimental. I have written the old readme keeping in mind that each step can be executed with either mapreduce or hive. The steps for execution are in /docs.

thank you sooo much!
